# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='FoodCategories',
        ),
    ]
