# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20171018_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=250)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='foodtype',
        ),
        migrations.DeleteModel(
            name='FoodCategories',
        ),
        migrations.DeleteModel(
            name='FoodDetails',
        ),
    ]
